theme: jekyll-theme-slate
description: This site displays our project's README file, which shows and explains the work we have done this trimester. 
It also displays of several code snippets from our main project.
